name: simple_service_container
description: Provides a service container and utilities for simple, non-lazy IOC.
version: 1.0.0-dev.2
repository: https://github.com/Oliphan/DartSimpleServiceContainer

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^6.0.0

dependencies:
  meta: ^1.16.0
